### ISSUE TITLE
System.DllNotFoundException: psapi.dll

### ISSUE THREAD

**Issue by BlueWinds** [0x1d7/VMMWSGC#1]
```
23:52:19.9670304 VMMWSGC [LOG] <SaveGameStructure.NotifyRefresh> Running post save refresh
23:52:19.9671589 VMMWSGC [LOG] Error emptying Private WorkingSet System.DllNotFoundException: psapi.dll
	  at (wrapper managed-to-native) VMMWSGC.Gc.EmptyWorkingSet(intptr)
	  at VMMWSGC.Gc.RunGc () [0x0000a] in <e20c450bbe03424499cbc1df9b3095a3>:0 
23:52:19.9671596 VMMWSGC [LOG] Please open an issue with the stack trace at https://github.com/0x1d7/VMMWSGC/issues
```

Unusure where psapi.dll is supposed to be, but pretty sure I don't have it anywhere in the game or mods folder.

```
blue@blue:~/Games/BATTLETECH$ find -name psapi.dll
blue@blue:~/Games/BATTLETECH$
```

BTA on linux, GOG version.

BlueWinds on the BTA Discord, if you want to hit me up, or of course can provide whatever information would be helpful here.

**Comment by 0x1d7** [comment]
`psapi.dll` is a Windows system DLL, shipped with Windows. [Wine](https://gitlab.winehq.org/wine/wine/-/tree/master/dlls/psapi?ref_type=heads) does implement the API by simply returning `true` rather than doing any work; based on the Wine source code I would assume it ships a `psapi.dll` file. I don't know what the GoG version ships with.

**Comment by BlueWinds** [comment]
BT has a linux native version which I'm running, no Wine involved at all.

**Comment by 0x1d7** [comment]
You'll want to disable the mod. This mod won't function for macOS/Linux anyway.

**Comment by BlueWinds** [comment]
Fair enough - I'll pass that on to Doves, thanks for the quick responses! Just saw the error in the logs and thought it worth submitting.
